#!/bin/sh

confdir="${XDG_CONFIG_HOME:=$HOME/.config}/discocss"
preloadFile="$confdir/preload.js"
cssFile="$confdir/custom.css"

mkdir -p "$confdir"

touch "$cssFile"

cat <<EOF > "$preloadFile"
(() => {
  const fs = require("fs");
  const cssFile = "$cssFile";
  const css = fs.readFileSync(cssFile);

  function inject({ document, window }) {
    window.addEventListener("load", () => {
      const style = document.createElement("style");
      style.innerHTML = css;
      document.head.appendChild(style);

      fs.watch(cssFile, {}, () => {
        style.innerHTML = fs.readFileSync(cssFile);
      });
    });
  }

  inject(require("electron").webFrame.context);
})();
EOF

ln -s "$preloadFile" /tmp/discocss-preload.js

sed -i 's|  // App preload script, used to provide a replacement native API now that|try { require\(`/tmp/discocss-preload.js`) } catch \(e\) {console.error\(e\);} |' \
    "$XDG_CONFIG_HOME"/discord/*/modules/discord_desktop_core/core.asar

command -v discord && exec discord
command -v Discord && exec Discord
